version: '3'
services: 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
    - 5672:5672
    - 8080:15672
  publisher:
    image: publisher
    container_name: publisher
    build: 
      context: .
      dockerfile: Dockerfiles/publisher.Dockerfile
    environment:
    - WATCH_PATH=/mnt/dir
    - RABBITMQ_HOST=rabbitmq
    - EXCHANGE=my-exchange
    - KEYS=python;docker
    volumes:
    - ./tmp:/mnt/dir
    depends_on:
    - rabbitmq
  .consumer:
    image: consumer
    build: 
      context: .
      dockerfile: Dockerfiles/consumer.Dockerfile
    environment:
    - CONSUMER_BROKER_HOST=rabbitmq
    - CONSUMER_EXCHANGE_NAME=my-exchange
  .mp-consumer:
    image: consumer-multiprocessing
    build: 
      context: .
      dockerfile: Dockerfiles/consumer-mp.Dockerfile
    environment:
    - CONSUMER_NUM_WORKERS=2
    - CONSUMER_BROKER_HOST=rabbitmq
    - CONSUMER_EXCHANGE_NAME=my-exchange
  python-consumer:
    extends: .consumer
    environment:
    - ROUTING_KEY=python
    depends_on:
    - rabbitmq
  docker-consumer:
    extends: .consumer
    environment:
    - CONSUMER_ROUTING_KEY=docker
    - CONSUMER_QUEUE_NAME=docker-queue
    depends_on:
    - rabbitmq
  docker-mp-consumer:
    extends: .mp-consumer
    environment:
    - CONSUMER_ROUTING_KEY=docker
    - CONSUMER_QUEUE_NAME=docker-queue
    depends_on:
    - rabbitmq

